"""Curated source collections shown on the setup page.

Each entry is ``(display name, careers page URL, target-company id)``.
``source_id`` stays ``None`` until the company is integrated as a target
company source; integrated companies render a switch bound to the existing
``target_companies`` setting.
"""

GERMAN_CHINESE_COMPANIES: tuple[tuple[str, str | None, str | None], ...] = (
    ("Huawei", "https://career.huawei.com/", None),
    ("ZTE", "https://job.zte.com.cn/", None),
    ("Xiaomi", "https://hr.xiaomi.com/", None),
    ("Lenovo", "https://jobs.lenovo.com/", None),
    ("Medion", "https://www.medion.com/de/karriere/stellenangebote.php", None),
    ("OPPO", "https://careers.oppo.com/", None),
    ("vivo", "https://career.vivo.com/", None),
    ("HONOR", "https://career.honor.com/", None),
    ("OnePlus", "https://www.oneplus.com/de/careers", None),
    ("DJI", "https://we.dji.com/jobs_en.html", None),
    ("TP-Link", "https://www.tp-link.com/de/about-us/career/", None),
    ("Dahua Technology", "https://www.dahuasecurity.com/about-dahua/career/join-the-team", None),
    ("Hytera Mobilfunk", "https://hmf-smart-solutions.de/en/jobs_en/", None),
    ("Anker", "https://career.anker-in.com/", None),
    ("Roborock", "https://www.linkedin.com/company/roborock/jobs", None),
    ("ECOVACS", "https://www.ecovacs.com/us/careers/job-list", None),
    ("Insta360", "https://www.insta360.com/jobs", None),
    ("TikTok", "https://lifeattiktok.com/", None),
    ("Alibaba Cloud", "https://www.alibabacloud.com/careers", None),
    ("China Telecom Europe", "https://careers.smartrecruiters.com/ChinaTelecomEuropeLimited", None),
    ("China Mobile International (CMI)", "https://www.cmi.chinamobile.com/en/join-us", None),
    ("Nexperia", "https://nexperia.wd3.myworkdayjobs.com/careers", "nexperia"),
    ("Haier", "https://haier.wd3.myworkdayjobs.com/en-US/HaierEurope_Professional_Careers", "haier"),
    ("Midea", "https://www.midea.com/de/karriere", None),
    ("Hisense", "https://de.hisense.com/karriere", None),
    ("Gorenje", "https://career2.successfactors.eu/career?company=gorenjegos&site_name=Hisense", None),
    ("TCL", "https://www.tcl.com/eu/en/career", None),
    ("BYD", "https://careers.bydeurope.com/", None),
    ("MG Motor", "https://www.mgmotor.de/career-overview", None),
    ("Maxus", "https://de.linkedin.com/company/maxomotive-deutschland-gmbh", None),
    ("XPeng", "https://www.xpeng.com/join-us", None),
    ("Omoda & Jaecoo", "https://www.omodajaecoo-auto.de/karriere", None),
    ("Lynk & Co", "https://careers.lynkco.com/", None),
    ("Zeekr", "https://zeekreu.teamtailor.com/", None),
    ("smart", "https://career.smart.com/", None),
    ("Lotus Cars", "https://careers.lotuscars.com/", None),
    ("Volvo Cars", "https://jobs.volvocars.com/", None),
    ("Polestar", "https://polestar.teamtailor.com/jobs", None),
    ("NIO", "https://www.nio.com/careers/jobs", None),
    ("Leapmotor", "https://careers.stellantis.com/job-search-results/", None),
    ("Leoni", "https://www.leoni.com/jobs-careers/job-portal", None),
    ("Grammer", "https://grammer-performance-management.csod.com/ux/ats/careersite/1/home?c=grammer-performance-management", None),
    ("Preh", "https://www.preh.com/karriere/stellenangebote", None),
    ("Joyson Safety Systems", "https://careers.joysonsafety.com", None),
    ("SEG Automotive", "https://www.seg-automotive.com/career/career-application-platform/", None),
    ("Kiekert", "https://www.kiekert.com/karriere/stellenangebote/", None),
    ("KACO", "https://kaco.de/karriere-bei-kaco/jobs/", None),
    ("Wegu", "https://wegu.de/category/jobs/", None),
    ("AMK Group", "https://amk-group.com/de/karriere/aktuelle-jobangebote/", None),
    ("Tristone Flowtech", "https://www.tristone.com/career/", None),
    ("KSM Castings", "https://karriere.ksmcastings.com/en/", None),
    ("Saargummi", "https://sgapply.powerappsportals.com/en-US/open-positions/", None),
    ("Yanfeng", "https://www.yanfeng.com/en/jobs", None),
    ("Fuyao Group", "https://job.fuyaogroup.com/fuyao/position/index?recruitmentType=SOCIALRECRUITMENT", None),
    ("Pirelli", "https://jobs.pirelli.com/", None),
    ("Hilite", "https://www.hilite.com/en/career/jobs", None),
    ("Continental Aerospace", "https://continental.aero/careers/", None),
    ("KUKA", "https://www.kuka.com/de-de/unternehmen/karriere/stellenangebote", None),
    ("KION Group", "https://kiongroup.wd3.myworkdayjobs.com/en-US/KIONGroup", None),
    ("Linde Material Handling", "https://kiongroup.wd3.myworkdayjobs.com/de-DE/KIONGroup", None),
    ("STILL", "https://www.still.de/beruf-karriere/stellenangebote.html", None),
    ("KraussMaffei", "https://jobs.kraussmaffei.com/", None),
    ("Putzmeister", "https://recruiting.putzmeister.com/de/jobs", None),
    ("Schwing Stetter", "https://schwing-stetter.com/de_de/unternehmen/ausbildung-karriere/schwing/stellenboerse.html", None),
    ("Sany Europe", "https://www.sanyeurope.com/jobs-2/", None),
    ("XCMG Europe", "https://www.linkedin.com/jobs/xcmg-europe-gmbh-jobs-worldwide", None),
    ("CREG Germany", "https://www.creg-germany.com/careers", None),
    ("Saurer", "https://dvinci.saurer.com/", None),
    ("Dürkopp Adler", "https://karriere.duerkopp-adler.com/", None),
    ("PFAFF Industrial", "https://www.pfaff-industrial.com/de/unternehmen/karriere", None),
    ("Waldrich Coburg", "https://www.waldrich-coburg.de/karriere/", None),
    ("KHD", "https://www.khd.com/career/", None),
    ("FFT", "https://jobs.fft.de/fft/go/fft-deutschland-alle-jobs/9308401/?locale=de_DE", None),
    ("Vossloh Locomotives", "https://vossloh.wd3.myworkdayjobs.com/Vossloh_External_Careers", "vossloh"),
    ("Ziegler", "https://www.ziegler.de/de/karriere/jobs-giengen/", None),
    ("Flex Power Tools", "https://www.flex-tools.com/de-de/karriere", None),
    ("WORX", "https://positec-europe.com/en/stellenangebote/", None),
    ("ZCCCT Europe", "https://www.zccct-europe.com/en/company/jobs-in-the-machining-industry/", None),
    ("Aweco", "http://www.aweco.de/jobs/stellenangebote", None),
    ("CATL (Germany/Europe)", "https://www.catl-career.com/", None),
    ("CATL (global)", None, None),
    ("Gotion High-Tech", "https://job-boards.greenhouse.io/gotion", None),
    ("Sungrow", "https://career-europe.sungrowpower.com/", None),
    ("LONGi", "https://www.longi.com/en/jobs/", None),
    ("Trina Solar", "https://careers.trinasolar.com/", None),
    ("JA Solar", "https://ja-solar.jobs.personio.de/", None),
    ("JinkoSolar", "https://www.jinkosolar.com/en/site/brand", None),
    ("EEW Energy from Waste", "https://www.eew-karriere.de/stellenangebote/", None),
    ("Syngenta", "https://jobs.syngenta.com/", None),
    ("ADAMA", "https://www.adama.com/deutschland/de/karriere", None),
    ("Bank of China (Germany)", "https://www.bankofchina.com/de/aboutus/ab4/", None),
    ("ICBC (Germany)", "http://www.icbc.de/cn/column/980127925339041793.html", None),
    ("China Construction Bank (Germany)", "http://www.ccb.com/lng/2026-03/16/article_2026031613413358949.shtml", None),
    ("Agricultural Bank of China", "https://career.abchina.com/", None),
    ("Bank of Communications (Germany)", "https://job.bankcomm.com", None),
    ("Minmetals (Germany)", None, None),
    ("Weiqiao Germany", "https://weiqiaogermany.de/karriere/", None),
    ("COSCO Shipping Lines", "https://lines.coscoshipping.com/home/Recruiting/recruiting/recruiting", None),
    ("OOCL", "https://www.oocl.com/eng/aboutoocl/ooclcareer/jobopportunity", None),
    ("Air China (Germany)", "https://www.airchina.de/DE/CN/about-us/recruitment/", None),
    ("H World", "https://int.hworld.com/career/vacancies/career/vacancies", None),
    ("Tom Tailor", "https://join.com/companies/tom-tailor", None),
    ("ASMPT SMT", "https://talents.smt.asmpt.com/Jobs?lang=eng", None),
    ("Milwaukee Tool (Europe)", "https://www.milwaukeetool.eu/careers/", None),
    ("Johnson Electric", "https://johnsonelectric.wd3.myworkdayjobs.com/Career_JE", "johnson-electric"),
    ("Kerry Logistics (KLN)", "https://www.kln.com/en/careers/job-opportunities/", None),
    ("Cathay Pacific", "https://careers.cathaypacific.com/en/careers/jobs", None),
    ("VTech (Germany)", "https://www.vtech.de/stellenangebote", None),
    ("TSMC", "https://ro.careers.tsmc.com/", None),
    ("Delta Energy Systems", "https://www.deltaenergysystems.com/de/delta-jobportal", None),
    ("HIWIN (Germany)", "https://www.hiwin.de/de/karriere-uebersicht/stellenangebote", None),
    ("Merida", "https://jobs.merida-centurion.com/de", None),
    ("Giant Bicycles", "https://www.giant-bicycles.com/de/jobs", None),
    ("ASUS", "https://join.com/companies/asuscom", None),
    ("Acer", "https://careers.acer.com/", None),
    ("MSI", "https://jobsemea.msi.com/", None),
    ("GIGABYTE", "https://www.gigabyte.com/de/Career", None),
    ("BenQ", "https://benqeuropebv.recruitee.com/", None),
    ("D-Link", "https://careers.smartrecruiters.com/DLinkSystemsInc", None),
    ("Zyxel", "https://www.zyxel.com/de/de/company/careers", None),
    ("QNAP", "https://www.qnap.com/de-de/career", None),
    ("Synology", "https://career.synology.com/", None),
    ("Advantech", "https://advantech.wd3.myworkdayjobs.com/en-US/External", "advantech"),
    ("Moxa", "https://tas-moxa.taleo.net/careersection/mx_ext/jobsearch.ftl?lang=en", None),
)
